In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
import pickle

In [20]:
## read the data
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [21]:
## drop the irrelevant features
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [22]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [23]:
## Encode the categorical value - gender
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [24]:
## Apply onehot encoder for Geography
onehot_encoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray() 
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [26]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [28]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [29]:
## Combine the data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [30]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [31]:
data.columns

Index(['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited',
       'Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype='str')

In [32]:
## split the data into features and target
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [34]:
X.columns

Index(['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'Exited', 'Geography_France',
       'Geography_Germany', 'Geography_Spain'],
      dtype='str')

In [35]:
y

0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: EstimatedSalary, Length: 10000, dtype: float64

In [36]:
##  split the data into raining and testing 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [37]:
## Scale the features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [38]:
## save the encoder and scaler File
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb')as file:
    pickle.dump(onehot_encoder_geo,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

### ANN Regression Problem

In [41]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [42]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)
])

## Compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

/Users/ganchi/ ANNClassification/venv/lib/python3.13/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [43]:
## setup the TensorBoard
log_dir="regression_logs/fit/"+datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [44]:
## Setup the earlystopping callbacks
early_stopping_callbacks=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [45]:
## train the model
history=model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=50,
    callbacks=[early_stopping_callbacks,tensorboard_callback]
)

Epoch 1/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100380.3594 - mae: 100380.3594 - val_loss: 98525.7422 - val_mae: 98525.7422
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - loss: 99654.0234 - mae: 99654.0234 - val_loss: 97055.7344 - val_mae: 97055.7344
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - loss: 97087.8906 - mae: 97087.8906 - val_loss: 93290.2734 - val_mae: 93290.2734
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - loss: 92030.6875 - mae: 92030.6875 - val_loss: 86982.0391 - val_mae: 86982.0391
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - loss: 84606.5547 - mae: 84606.5547 - val_loss: 78739.1953 - val_mae: 78739.1953
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - loss: 75767.3047 - mae: 75767.3047 - val_loss: 70069.6406 - val_mae: 70069.6406
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - loss: 67034.3594 - mae: 67034.3594 - val_loss: 62351.1055 - val_mae: 62351.1055
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - loss: 59892.2227 - mae: 59892.2227 - val_loss: 56697.5781 - val_mae: 56697.5781
Epoch 9/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 55142.9375 - mae: 55142.9375 - val_loss: 53342.9492 - val_mae: 53342.9492
Epoch 10/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 52452.5586 - mae: 52452.5586 - val_loss: 51778.8711 - val_mae: 51778.8711
Epoch 11/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51137.2852 - mae: 51137.2852 - val_loss: 51176.3945 - val_mae: 51176.3945
Epoch 12/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50617.6406 - mae: 50617.6406 - val_loss: 50984.7617 - val_mae: 50984.7617
Epoch 13/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50386.3086 - mae: 50386.3086 - val_loss: 50881.5234 - val_mae: 50881.5234
Epoch 14/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 981us/step - loss: 50262.1055 - mae: 50262.1055 - val_loss: 50806.7812 - val_mae: 50806.7812
Epoch 15/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - loss: 50191.2227 - mae: 50191.2227 - val_loss: 50753.6719 - val_mae: 50753.6719
Epoch 16/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - loss: 50127.5781 - mae: 50127.5781 - val_loss: 50692.4258 - val_mae: 50692.4258
Epoch 17/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - loss: 50076.9219 - mae: 50076.9219 - val_loss: 50653.7266 - val_mae: 50653.7266
Epoch 18/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - loss: 50032.7188 - mae: 50032.7188 - val_loss: 50607.7969 - val_mae: 50607.7969
Epoch 19/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - loss: 49991.1406 - mae: 49991.1406 - val_loss: 50579.2695 - val_mae: 50579.2695
Epoch 20/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - loss: 49955.1133 - mae: 49955.1133 - val_loss: 50548.5859 - val_mae: 50548.5859
Epoch 21/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - loss: 49919.6211 - mae: 49919.6211 - val_loss: 50516.7461 - val_mae: 50516.7461
Epoch 22/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - loss: 49891.6836 - mae: 49891.6836 - val_loss: 50487.7969 - val_mae: 50487.7969
Epoch 23/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - loss: 49867.9062 - mae: 49867.9062 - val_loss: 50466.7773 - val_mae: 50466.7773
Epoch 24/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - loss: 49839.5859 - mae: 49839.5859 - val_loss: 50441.2383 - val_mae: 50441.2383
Epoch 25/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - loss: 49814.6719 - mae: 49814.6719 - val_loss: 50439.0195 - val_mae: 50439.0195
Epoch 26/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - loss: 49791.2070 - mae: 49791.2070 - val_loss: 50415.5352 - val_mae: 50415.5352
Epoch 27/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49768.8164 - mae: 49768.8164 - val_loss: 50399.0195 - val_mae: 50399.0195
Epoch 28/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - loss: 49751.0078 - mae: 49751.0078 - val_loss: 50396.3789 - val_mae: 50396.3789
Epoch 29/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - loss: 49732.2773 - mae: 49732.2773 - val_loss: 50376.6602 - val_mae: 50376.6602
Epoch 30/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - loss: 49717.7109 - mae: 49717.7109 - val_loss: 50369.9258 - val_mae: 50369.9258
Epoch 31/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - loss: 49700.6016 - mae: 49700.6016 - val_loss: 50359.1992 - val_mae: 50359.1992
Epoch 32/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - loss: 49683.8516 - mae: 49683.8516 - val_loss: 50352.0469 - val_mae: 50352.0469
Epoch 33/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - loss: 49671.8008 - mae: 49671.8008 - val_loss: 50324.4297 - val_mae: 50324.4297
Epoch 34/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - loss: 49655.4609 - mae: 49655.4609 - val_loss: 50332.0469 - val_mae: 50332.0469
Epoch 35/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - loss: 49642.7109 - mae: 49642.7109 - val_loss: 50320.2305 - val_mae: 50320.2305
Epoch 36/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - loss: 49632.0273 - mae: 49632.0273 - val_loss: 50317.1875 - val_mae: 50317.1875
Epoch 37/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - loss: 49619.7305 - mae: 49619.7305 - val_loss: 50312.3711 - val_mae: 50312.3711
Epoch 38/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49608.0508 - mae: 49608.0508 - val_loss: 50309.8320 - val_mae: 50309.8320
Epoch 39/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49597.9844 - mae: 49597.9844 - val_loss: 50305.7578 - val_mae: 50305.7578
Epoch 40/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49587.4336 - mae: 49587.4336 - val_loss: 50299.7109 - val_mae: 50299.7109
Epoch 41/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49580.0312 - mae: 49580.0312 - val_loss: 50300.7930 - val_mae: 50300.7930
Epoch 42/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49566.9023 - mae: 49566.9023 - val_loss: 50294.8203 - val_mae: 50294.8203
Epoch 43/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49560.7734 - mae: 49560.7734 - val_loss: 50296.6641 - val_mae: 50296.6641
Epoch 44/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49547.7266 - mae: 49547.7266 - val_loss: 50292.6484 - val_mae: 50292.6484
Epoch 45/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49541.9805 - mae: 49541.9805 - val_loss: 50287.4141 - val_mae: 50287.4141
Epoch 46/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - loss: 49533.4336 - mae: 49533.4336 - val_loss: 50284.8867 - val_mae: 50284.8867
Epoch 47/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - loss: 49527.2656 - mae: 49527.2656 - val_loss: 50279.3633 - val_mae: 50279.3633
Epoch 48/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - loss: 49517.7734 - mae: 49517.7734 - val_loss: 50282.9570 - val_mae: 50282.9570
Epoch 49/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - loss: 49510.5352 - mae: 49510.5352 - val_loss: 50289.6445 - val_mae: 50289.6445
Epoch 50/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - loss: 49502.9219 - mae: 49502.9219 - val_loss: 50277.3828 - val_mae: 50277.3828

In [46]:
%load_ext tensorboard

In [48]:
%tensorboard --logdir regression_logs/fit

Reusing TensorBoard on port 6006 (pid 4066), started 0:03:05 ago. (Use '!kill 4066' to kill it.)

In [49]:
## Evaluate the model on test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f"Test MAE: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step - loss: 50277.3828 - mae: 50277.3828
Test MAE: 50277.3828125

In [50]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.